repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.5.0
    hooks:
    -   id: clang-format
        name: clang-format
        language: system
        types: [file]
        entry: clang-format -i --style=file --fallback-style=Google $files

-   repo: https://github.com/marketplace/actions/cppcheck
    rev: v1.1.3
    hooks:
    -   id: cppcheck
        name: cppcheck
        entry: cppcheck
        language: system
        files: '\.(c|cpp|h|hpp)$'
        additional_dependencies: [cppcheck]

-   repo: https://github.com/jthomas/cppcheck-action
    rev: v1.1.0
    hooks:
    -   id: cppcheck-github-action
        name: cppcheck-github-action
        entry: cppcheck-github-action
        files: '\.(c|cpp|h|hpp)$'
